apiVersion: v1
kind: Namespace
metadata:
  name: infrawatch
  labels:
    app.kubernetes.io/name: infrawatch
    app.kubernetes.io/managed-by: kustomize
---
apiVersion: v1
kind: Namespace
metadata:
  name: infrawatch-monitoring
  labels:
    app.kubernetes.io/name: infrawatch-monitoring
    app.kubernetes.io/managed-by: kustomize
---
apiVersion: v1
kind: Namespace
metadata:
  name: infrawatch-data
  labels:
    app.kubernetes.io/name: infrawatch-data
    app.kubernetes.io/managed-by: kustomize
